### ISSUE TITLE
[Display News, List View] Incorrect size of the news item's Title text with 1 row and Description text with 3 rows

### ISSUE THREAD

**Issue by tatiana404** [ita-social-projects/GreenCity#1897] opened 2020-11-20 22:27 UTC
Environment:
Microsoft Windows 10 Home, Version 10.0.19041
Google Chrome Version 86.0.4240.198 (Official Build) (64-bit);
Windows 10 Pro, Mozilla Firefox 82.0.3 (64-біт)
Reproducible: always
Build found: 20.11.2020

Preconditions
1. https://ita-social-projects.github.io/GreenCityClient/ is opened.
2. News items are created in the DB and are displayed as first news item in the list view. Use queries:
INSERT INTO eco_news
(ID, title, text, author_id, creation_date)
VALUES (724, 'Lorem ipsum dolor sit amet, consectetuer',
'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure d',
857, '<current date and time in format e.g. "2020-05-17 10:00:00.000000">');

INSERT INTO eco_news_tags
(eco_news_id, tags_id)
VALUES (724, 1), (724, 2);

Steps to reproduce

1. Click on 'Eco news' link in the header.
2. Set browser window width to 1440px.
3. Click on the View as a List option on the right side of the page.
4. Pay attention to created news' Title and Description display.

Actual result
Title is displayed and consist of 1 row and is 26px in heights.
![Title 1 row](https://user-images.githubusercontent.com/65060199/99855738-26225000-2b90-11eb-8b5b-cc56ecfe259b.jpg)
Description is displayed and consist of 3 rows and is 69px in heights.
![description 3 rows](https://user-images.githubusercontent.com/65060199/99855753-2de1f480-2b90-11eb-88d5-bebf143150b3.jpg)

Expected result
Title is displayed and consist of 1 row and is 32px in heights.
Description is displayed and consist of 3 rows and is 96px in heights.

Postconditions
 1. Created news are deleted from DB using queries:
DELETE FROM eco_news_tags
WHERE eco_news_id = 724;

DELETE FROM eco_news
WHERE id = 724;

User story and test case links
E.g.: "User story #460
[Test case](https://jira.softserve.academy/browse/GC-724)

**Comment by JimHolman1199** [comment] 2020-12-13 13:19
![Screenshot 2020-12-13 at 15 15 31](https://user-images.githubusercontent.com/46226026/102013007-0e388900-3d56-11eb-9f2a-2dba1ec4ad4e.png)
![Screenshot 2020-12-13 at 15 15 45](https://user-images.githubusercontent.com/46226026/102013011-142e6a00-3d56-11eb-976d-b73bcc79ba55.png)
this is not a bug
check the design again

moreover, the height of the containers should not be the purpose of testing because the containers can dynamically change the height and width

**Comment by JimHolman1199** [comment] 2020-12-13 13:20
but I see a bug in the line heigth of text, so I'll fix it

**Comment by irynamykhailevych** [comment] 2021-05-01 18:15
Fixed in accordance with the new mockup design.

**Closed by irynamykhailevych** 2021-05-01 18:15 UTC
Labels: Bug, Display news, Pri: medium, Sev: minor, UI, points: 1
