### ISSUE TITLE
[My habits] Habit  isn't automatically transferred to the section of 'Acquired habits' from 'Habits in progress'  if it has 100% progress

### ISSUE THREAD

**Issue by VasylynaYaremkiv** [ita-social-projects/GreenCity#2243] opened 2021-01-29 18:54 UTC
Environment:** OS Windows 10, Mac OS, browsers: Google Chrome, Mozilla Firefox.
Reproducible: always.
Build found:29.01.2021
E.g. "commit 147fa44"

Preconditions
Precondition:
1. Registered User is logged in;
2. User has at least one 'Habits in progress', where (duration=habit_streak-1).

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/
2. Go to 'My Habits' page.
3. Click "Mark as done" switcher of 'Habits in progress', where duration=habit_streak-1

**Actual result**
1.Habit  isn't automatically transferred to the section of 'Acquired habits' from 'Habits in progress'  if it has 100% progress
2."Habit_streak" and 'Duration' is represented on card of 'Habits in progress'.
3. 'Mark as done' switcher is is represented on card of 'Habits in progress'
4. 'Mark as done' label is s represented on card of 'Habits in progress'

**Expected result**
1.Habbit is automatically transferred to the section of 'Acquired habits', and not represented in 'Habits in progress'.
Counter of 'Habits progress': -1.Counter of 'Acquired habits': +1
2.'Duration' is represented on card of 'Acquired habits'.
3.Star' icon is represented on card of 'Acquired habits'.
4."Great! You've got a habit!" text is represented on card of 'Acquired habits'.

**User story and test case links**
E.g.: "User story #1160  https://github.com/ita-social-projects/GreenCity/issues/1160
[Test case GC-1816 ](https://jira.softserve.academy/projects/GC?selectedItem=com.thed.zephyr.je:zephyr-tests-page#test-cycles-tab)"

**Labels to be added**
"Bug", 
Priority ("pri: high"), 
Severity ("severity:major"), 
Type "UI,

Attachments:
**Actual result**
![Actual result](https://user-images.githubusercontent.com/77506104/106315487-f66c8400-6273-11eb-94bf-2925a9c8bb17.png)

expected result
![expected result](https://user-images.githubusercontent.com/77506104/106315489-f79db100-6273-11eb-85d1-7b0ea386dea0.png)

pre-condition
![pre-condition](https://user-images.githubusercontent.com/77506104/106315491-f79db100-6273-11eb-85b0-7ec52eb234a8.png)

**Comment by OksanaRom** [comment] 2021-04-16 09:21
**Steps to reproduce**
1. Mark as 'Done' any habit on my habits list
2. Check if it is automatically marked as 'Done' in a pop-up in the calendar
3.  Mark as 'Done' any habit in a pop-up in the calendar
4. Check if it is automatically marked as 'Done' on my habits list

**Actual result:**
Habit isn`t marked as done automatically. It is marked as done only after refreshing the page
**Expected result:**
Habit is marked as done automatically

**Comment by yuriiLisunov** [comment] 2021-04-20 13:34
OksanaRom, this bug was about inprogress --> acquired habit, but not about connection with calendar popup!

**Comment by irynamykhailevych** [comment] 2021-05-01 19:52
Cannot reproduce this bug. The new bug is found #2709

**Comment by SerhiiStarshoi** [comment] 2021-06-08 07:43
Defect is still presented. Habit isn't automatically transferred to the section of 'Acquired habits' from 'Habits in progress' 

<img width="883" alt="image" src="https://user-images.githubusercontent.com/32453285/121143730-07db2380-c846-11eb-9844-6080c8157d65.png">

**Comment by KaterynaKhorosh** [comment] 2022-01-20 09:52
1.Habbit is automatically transferred to the section of 'Acquired habits', and not represented in 'Habits in progress'.
Counter of 'Habits progress': -1.Counter of 'Acquired habits': +1
2.'Duration' is represented on card of 'Acquired habits'.
3.Star' icon is represented on card of 'Acquired habits'.
4."Great! You've got a habit!" text is represented on card of 'Acquired habits'.

https://user-images.githubusercontent.com/95848159/150315176-89166700-2041-4e6c-aa5f-8dff52abf003.mp4

**Closed by KaterynaKhorosh** 2022-01-20 09:52 UTC
Labels: Pri: high, Bug, Sev: major, UI, Habit item
