### ISSUE TITLE
[Admin.Orders] The sort in asc/desc order buttons are not functional

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#4068] opened 2022-05-05 10:04 UTC
**Environment:** Windows 10, Google Chrome 101
**Reproducible:** always
**Build found:** 05.05.2022

**Preconditions**
Go to https://ita-social-projects.github.io/GreenCityClient/#/
Sign in as admin

**Steps to reproduce**
1.Click the 'UBS-admin' button in pop-up window
2.Click the 'Orders' button
3.Click the arrow in the any field
4.Take a look if the information is sorted in descending/ascending order

**Actual result**
The sort in asc/desc order buttons are not functional

**Expected result**
By clicking on the sorting button the information is sorted in descending/ascending order

**Comment by krayevska** [comment] 2022-06-07 16:36
duplicate of https://github.com/ita-social-projects/GreenCity/issues/4065

**Closed as completed by krayevska** 2022-06-07 16:36 UTC
Labels: Bug, Functional, GreenCityUBS, UBS admin, UBS orders
