### ISSUE TITLE
[UBS-User] The addresses fields are disabled if user wants to add address

### ISSUE THREAD

**Issue by julialytsus** [ita-social-projects/GreenCity#4619] opened 2022-09-20 15:03 UTC
**Environment:** macOS Monterey 12.5, Safari 16.0
**Reproducible:** sometimes 
**Build found:** 20.09.2022
**Priority:** Medium
**Severity:** Major

**Preconditions**
1. User should be authorized
2. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs

**Steps to reproduce**
1. Go to 'UBS-user' clicked on your name in upper right corner 
2. Click on 'User data' -> 'Edit data' -> 'Add address'

**Actual result**
The addresses fields are disabled
<img width="1425" alt="Знімок екрана 2022-09-16 о 11 06 04" src="https://user-images.githubusercontent.com/112894449/191288742-a7fcd08a-24c0-4a13-95d7-937419eb7784.png">

**Expected result**
The addresses fields are able 

https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=13929%3A66508

**Comment by marianaharnyk** [comment] 2022-10-01 10:52
This is a duplicate of task #4551

**Closed as completed** 2022-10-01 10:53 UTC
Labels: Pri: medium, Bug, Sev: major, Functional, UBS, GreenCityUBS, ubs-user
