### ISSUE TITLE
[Event] A notification about successfully joining the event does not appear

### ISSUE THREAD

**Issue by GitVladyslav** [ita-social-projects/GreenCity#4588] opened 2022-09-15 17:53 UTC
**Environment:** 
Windows 10 Домашняя 21H2
Google Chrome Version 104.0.5112.82 (64-bit)
**Reproducible:** always
**Build found:** 9.09.2022

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/GreenCityClient/#/events
2. Log in
3. Select an open-type event from the list
4. Click the "Join event" button on the event card

**Actual result**
The notification "You have successfully joined the event" does not appear

**Expected result**
The notification "You have successfully joined the event" should appear

**User story and test case links**
"User story #3193 
[Test case](https://jira.softserve.academy/browse/GC-3118)"

**Comment by DanaIuich** [comment] 2023-05-29 09:45
The notification "You have successfully joined the event" does not appear

**Comment by darinadobrukha** [comment] 2023-06-02 08:07
duplicate of [[Events] There is no message after joining event #5775

**Closed as completed** 2023-10-12 14:52 UTC
Labels: Pri: medium, Bug, Sev: minor, Functional, event, GreenCityEvent, Events
