### ISSUE TITLE
[API][Client-controller-documentation Bug] Body in response 200 status code for endpoint greencity-ubs.testgreencity.ga/ubs/client/user-orders  does not match API-documentation 

### ISSUE THREAD

**Issue by Horokh** [ita-social-projects/GreenCity#4531] opened 2022-08-13 06:13 UTC
**Environment:** Windows 10 Pro,  Opera  89.0.4447.83
**Reproducible:** always
**Build found:** 13.08.2022

**Preconditions**
User is authorized. 
User has at least one order.

**Steps to reproduce**
Send Get  by using request 
https://greencity-ubs.testgreencity.ga/ubs/client/user-orders

**Actual result**
{
  "page": [
    {
      "id": 1188,
      "dateForm": "2022-08-09T14:44:15.53951",
      "datePaid": "2022-08-09T14:44:15.53951",
      "orderStatus": "Сформовано",
      "orderStatusEng": "Formed",
      "paymentStatus": "Оплачено",
      "paymentStatusEng": "Paid",
      "paidAmount": 600,
      "orderFullPrice": 600,
      "amountBeforePayment": 0,
      "bags": [
        {
          "service": "Безпечні відходи",
          "serviceEng": "Safe waste",
          "capacity": 120,
          "fullPrice": 250,
          "count": 1,
          "totalPrice": 250
        },
        {
          "service": "Текстильні відходи",
          "serviceEng": "Textile waste",
          "capacity": 120,
          "fullPrice": 300,
          "count": 1,
          "totalPrice": 300
        },
        {
          "service": "Текстильні відходи",
          "serviceEng": "Textile waste",
          "capacity": 20,
          "fullPrice": 50,
          "count": 1,
          "totalPrice": 50
        }
      ],
      "orderComment": "",
      "bonuses": 0,
      "certificate": [],
      "additionalOrders": [],
      "sender": {
        "senderName": "Петро",
        "senderSurname": "Петроивич",
        "senderEmail": "prophotolviv@gmail.com",
        "senderPhone": "+380504140121"
      },
      "address": {
        "addressCity": "Київ",
        "addressCityEng": "Kyiv",
        "addressRegion": "Київська область",
        "addressRegionEng": "Kyivs'ka oblast'",
        "addressStreet": "вулиця Петра Запорожця",
        "addressStreetEng": "Petra Zaporozhtsya Street",
        "addressDistinct": "Дніпровський район",
        "addressDistinctEng": "Dniprovs'kyi District",
        "addressComment": "У дворі",
        "houseNumber": "12",
        "houseCorpus": "1",
        "entranceNumber": "1"
      }
    },

**Expected result**
[
  {
    "addressComment": "string",
    "addressExportDetailsDto": {
      "addressCity": "string",
      "addressDistrict": "string",
      "addressEntranceNumber": "string",
      "addressHouseCorpus": "string",
      "addressHouseNumber": "string",
      "addressId": 0,
      "addressRegion": "string",
      "addressStreet": "string"
    },
    "amountOfBagsConfirmed": {
      "additionalProp1": 0,
      "additionalProp2": 0,
      "additionalProp3": 0
    },
    "amountOfBagsExported": {
      "additionalProp1": 0,
      "additionalProp2": 0,
      "additionalProp3": 0
    },
    "amountOfBagsOrdered": {
      "additionalProp1": 0,
      "additionalProp2": 0,
      "additionalProp3": 0
    },
    "bags": [
      {
        "capacity": 0,
        "id": 0,
        "name": "string",
        "nameEng": "string",
        "price": 0
      }
    ],
    "certificates": [
      "string"
    ],
    "comment": "string",
    "courierInfo": {
      "courierLimit": "LIMIT_BY_SUM_OF_ORDER",
      "maxAmountOfBigBags": 0,
      "maxPriceOfOrder": 0,
      "minAmountOfBigBags": 0,
      "minPriceOfOrder": 0
    },
    "courierPricePerPackage": 0,
    "employeePositionDtoRequest": {
      "allPositionsEmployees": {
        "additionalProp1": [
          {
            "id": 0,
            "name": "string"
          }
        ],
        "additionalProp2": [
          {
            "id": 0,
            "name": "string"
          }
        ],
        "additionalProp3": [
          {
            "id": 0,
            "name": "string"
          }
        ]
      },
      "currentPositionEmployees": {
        "additionalProp1": "string",
        "additionalProp2": "string",
        "additionalProp3": "string"
      },
      "orderId": 0
    },
    "exportDetailsDto": {
      "allReceivingStations": [
        {
          "createDate": "string",
          "createdBy": "string",
          "id": 0,
          "name": "string"
        }
      ],
      "dateExport": "string",
      "receivingStationId": 0,
      "timeDeliveryFrom": "string",
      "timeDeliveryTo": "string"
    },
    "generalOrderInfo": {
      "adminComment": "string",
      "dateFormed": "2022-08-13T06:10:02.125Z",
      "id": 0,
      "orderPaymentStatus": "PAID",
      "orderPaymentStatusName": "string",
      "orderPaymentStatusNameEng": "string",
      "orderPaymentStatusesDto": [
        {
          "eng": "string",
          "key": "string",
          "ua": "string"
        }
      ],
      "orderStatus": "FORMED",
      "orderStatusName": "string",
      "orderStatusNameEng": "string",
      "orderStatusesDtos": [
        {
          "ableActualChange": true,
          "eng": "string",
          "key": "string",
          "ua": "string"
        }
      ]
    },
    "numbersFromShop": [
      "string"
    ],
    "orderBonusDiscount": 0,
    "orderCertificateTotalDiscount": 0,
    "orderDiscountedPrice": 0,
    "orderExportedDiscountedPrice": 0,
    "orderExportedPrice": 0,
    "orderFullPrice": 0,
    "paymentTableInfoDto": {
      "overpayment": 0,
      "paidAmount": 0,
      "paymentInfoDtos": [
        {
          "amount": 0,
          "comment": "string",
          "id": 0,
          "imagePath": "string",
          "paymentId": "string",
          "receiptLink": "string",
          "settlementdate": "string"
        }
      ],
      "unPaidAmount": 0
    },
    "userInfoDto": {
      "customerEmail": "string",
      "customerName": "string",
      "customerPhoneNumber": "string",
      "customerSurName": "string",
      "recipientEmail": "string",
      "recipientId": 0,
      "recipientName": "string",
      "recipientPhoneNumber": "string",
      "recipientSurName": "string",
      "totalUserViolations": 0,
      "userViolationForCurrentOrder": 0
    }
  }
]

**User story and test case links**
ubs.testgreencity.ga/swagger-ui.html#/client-controller/getAllDataForOrderUsingGET
**Labels to be added**
"Bug",  "API" "Documetation"

**Comment by OlegVat** [comment] 2022-09-23 12:40
I am closing this issue because of the difference between schema and API response,  this is not a bug it's expected behavior.

**Closed as completed by OlegVat** 2022-09-23 12:40 UTC
Labels: back-end, Bug, Documentation, GreenCity, UBS Personal Cabinet
