### ISSUE TITLE
[Request Page] After clicking on friend's request card user is not redirected to user's page

### ISSUE THREAD

**Issue by lerakhmullaeva** [ita-social-projects/GreenCity#6281] opened 2023-08-26 13:04 UTC
**Environment:** Windows 10, Chrome 114.0.5735.110 (64 bit)
**Reproducible:** always
**Build found:** 22.08.23

**Preconditions**
User has received at least 1 friend request.

**Steps to reproduce**

1. Go to [GreenCity](https://www.greencity.social/#/profile/309/friends/requests).
2. Sign in as User.
3. Open My Friend page.
4. Click on Requests page.
5. Click on friend's request card.

**Actual result**
User redirects to [UBS Page](https://www.greencity.social/#/ubs?tab=All%20firends&index=3).

**Expected result**
User redirects to page of user who has sent a request.

**User story and test case links**
E.g.: "User story #2084
[Test case](https://jira.softserve.academy/browse/4214)

**Comment by Oleksandra-Kobets** [comment] 2023-09-29 19:12
this is duplicate of this card:
https://github.com/ita-social-projects/GreenCity/issues/6283

**Closed as completed** 2023-09-29 19:12 UTC
Labels: Pri: high, Bug, Sev: major, Functional, Friend list
