### ISSUE TITLE
[Request Page] User can not accept friend request on User's page because system no not redirects to User's page

### ISSUE THREAD

**Issue by lerakhmullaeva** [ita-social-projects/GreenCity#6282] opened 2023-08-26 13:06 UTC
**Environment:** Windows 10, Chrome 114.0.5735.110 (64 bit)
**Reproducible:** always
**Build found:** 22.08.23

**Preconditions**
User has received at least 1 user request.

**Steps to reproduce**
Go to [GreenCity](https://www.greencity.social/#/profile/309/friends/requests).
Sign in as User.
Open My Friend page.
Click on Requests page.
Click on friend's request card.

**Actual result**
User redirects to [UBS Page](https://www.greencity.social/#/ubs?tab=All%20firends&index=3).

**Expected result**
User redirects to page of user who has sent a friend request and able to accept/decline request from User's page.

**User story and test case links**
E.g.: "User story #2084 
[Test case](https://jira.softserve.academy/browse/4222)

**Comment by Oleksandra-Kobets** [comment] 2023-09-29 19:13
this is duplicate of this card:
https://github.com/ita-social-projects/GreenCity/issues/6283

**Closed as completed by Oleksandra-Kobets** 2023-09-29 19:13 UTC
Labels: Pri: high, Bug, Sev: major, Functional, Friend list
