### ISSUE TITLE
[Eco News page] Title isn't displayed fully after selecting list view option 

### ISSUE THREAD

**Issue by NatalyaBranets** [ita-social-projects/GreenCity#553] opened 2020-04-06 22:46 UTC
Steps to reproduce: 
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/news
2. Click on 'List view' option.

Actual result: Title is cut. 
Expected result: Title should be displayed fully. 

Actual: ![Actual result title cut](https://user-images.githubusercontent.com/63067366/78611970-d4cb8780-7870-11ea-9bb8-ef22c18dddad.jpg)
![Actual result title cut open news](https://user-images.githubusercontent.com/63067366/78611984-dc8b2c00-7870-11ea-8966-10e397d8a106.jpg)
Expected: 
<img width="561" alt="74435211-9e731c80-4e6c-11ea-8f92-2a72040675aa" src="https://user-images.githubusercontent.com/63067366/79137989-6af53580-7dbc-11ea-8aa6-7b6bb9a9415a.png">

**Comment by KimAT25** [comment] 2020-04-24 10:39
Duplicate of bug #556

**Closed by KimAT25** 2020-04-24 10:39 UTC
Labels: API, Bug, news page, pri: medium, severity:manor
