### ISSUE TITLE
[Display News, List View] Incorrect display of the text of Title with 3 rows and Description with 1 row

### ISSUE THREAD

**Issue by tatiana404** [ita-social-projects/GreenCity#1891] opened 2020-11-20 00:49 UTC
Environment: 
Microsoft Windows 10 Home, Version 10.0.19041
Google Chrome Version 86.0.4240.198 (Official Build) (64-bit);
Windows 10 Pro, Mozilla Firefox 82.0.3 (64-біт)
Reproducible: always
Build found: 20.11.2020

Preconditions

1. https://ita-social-projects.github.io/GreenCityClient/ is opened.
2. News items are created in the DB and are displayed as first news item in the list view. Use queries:
INSERT INTO eco_news
(ID, title, text, author_id, creation_date)
VALUES (723, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim ven',
'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure d',
857, '<current date and time in format e.g. "2020-05-17 10:00:00.000000">');

INSERT INTO eco_news_tags
(eco_news_id, tags_id)
VALUES (723, 1), (723, 2);

Steps to reproduce

1. Click on 'Eco news' link in the header. 
2. Set browser window width to 1440px.
3. Click on the View as a List option on the right side of the page.
4. Pay attention to created news Title and Description display.

Actual result
Title is displayed and consist of 3 rows and is 77px in heights.
![title height](https://user-images.githubusercontent.com/65060199/99741632-5a3b3980-2ada-11eb-893c-973f27c7687c.jpg)
Description is displayed and consist of 1 row and is 69px in heights.
![description height](https://user-images.githubusercontent.com/65060199/99741651-63c4a180-2ada-11eb-9ea4-a8582f1c824d.jpg)

Expected result
Title is displayed and consist of 3 rows and is 96px in heights.
Description is displayed and consist of 1 row and is 32px in heights.

Postconditions
 Created news are deleted from DB using queries:
DELETE FROM eco_news_tags
WHERE eco_news_id = 723;
DELETE FROM eco_news
WHERE id = 723;

User story and test case links
E.g.: "User story #460
[Test case](https://jira.softserve.academy/browse/GC-723)

**Comment by JimHolman1199** [comment] 2020-12-13 13:13
![Screenshot 2020-12-13 at 15 12 20](https://user-images.githubusercontent.com/46226026/102012912-99fde580-3d55-11eb-9e68-bbccc5d4ad43.png)
according to the design: 1 row for Title and 2 rows for desc...
this is not a bug..

**Comment by oprotyniak** [comment] 2020-12-13 17:17
Here the bug report  is related to news with 3 row title and 1 row description. Did you try reproducing this bug with the given queries for database?

**Comment by JimHolman1199** [comment] 2020-12-13 22:51
I don't care about the database if only 1 row with a title is possible on frontend when screen width more than 1440 pixels

**Comment by TetianaD** [comment] 2021-04-28 12:47
**Actual result:**
Title is displayed and consists of 3 rows and is 78px in height.
![photo_2021-04-28_15-42-55](https://user-images.githubusercontent.com/10379945/116405774-af713900-a838-11eb-9a54-d154e3896b3b.jpg)
Description is displayed and consists of 1 row and is 21px in height.
![photo_2021-04-28_15-44-12](https://user-images.githubusercontent.com/10379945/116405801-ba2bce00-a838-11eb-8868-27c3ca22f7d5.jpg)

**Expected result:**
Title is displayed and consists of 3 rows and is 96px in height.
Description is displayed and consists of 1 row and is 32px in height.

<img width="735" alt="Screenshot 2021-04-28 at 15 31 36" src="https://user-images.githubusercontent.com/10379945/116404835-b186c800-a837-11eb-99e7-10ab4b6d1673.png">

"User story #460

**Comment by TetianaD** [comment] 2021-04-30 16:26
Fixed in accordance with the new mockup design.

**Closed by TetianaD** 2021-04-30 16:26 UTC
Labels: Bug, Functional, Pri: medium, Sev: minor, UI
