### ISSUE TITLE
[Create news] 'Publish' button appears on the 'Preview' page if no tags are selected

### ISSUE THREAD

**Issue by traviscolt** [ita-social-projects/GreenCity#709] opened 2020-05-17 17:00 UTC
**Environment:** Windows 8.1 x64, Mozilla Firefox 76.0 (64-bit),  Google Chrome
Версія 81.0 (64-bit)
**Reproducible:** always
**Build found:** commit b517ccb

**Steps to reproduce:**

1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Log into the system.
3. Click on 'Eco news' link in the header.
4. Click on 'Create news' button.
5. Enter valid values in 'Title' text field and 'Content' text field
6. Click the 'Preview' button

**Actual result:**
'Publish' button appears
![Screenshot_7](https://user-images.githubusercontent.com/35031131/82154706-476c5180-9878-11ea-8426-ef240f7ce449.jpg)

**Expected result:**
'Publish' button doesn't appear on preview if there are no tags choose
![Screenshot_8](https://user-images.githubusercontent.com/35031131/82154712-4d623280-9878-11ea-9186-550ff05ec9c9.jpg)

User story #548

**Comment by ihordubas** [comment] 2020-05-26 16:58
duplicate of #688

**Closed by ihordubas** 2020-05-26 16:58 UTC
Labels: Bug, Functional, pri: low, severity:manor
