### ISSUE TITLE
Bug [Admin]: Wrong name of 'Create new place' button

### ISSUE THREAD

**Issue by Mari1ana** [ita-social-projects/GreenCity#289] opened 2019-10-29 17:27 UTC
Steps to reproduce:
1. Go to http://greencityclient.herokuapp.com/.
2. Login as Admin.
3. Click on dropdown list of 'Admin' button on the top right corner of the window.
4. Select 'Admin'.
5. Select 'Place' tab.
6. Pay attention to the name of the 'Create new place' button on the top right corner of the window.

Actual result:
Button is named 'Create new cafe'.

Expected result:
Button is named 'Create new place'.

![Admin 'Create new place' button](https://user-images.githubusercontent.com/57095740/67793813-3860b600-fa84-11e9-82c5-ca35988cd42a.png)

https://ssu-jira.softserveinc.com/browse/GCS-44

**Comment by Bastarn78** [comment] 2019-11-06 11:56
This bug has already been created. Please check previous bugs. thank you. 
[https://github.com/SoftServe-Social-Projects/GreenCity/issues/286](url)

**Comment by greatpanda1603** [comment] 2020-06-24 20:40
As per comment above, this bug was a duplicate of already closed bug #286.
It lost its relevance since Admin panel is not currently supported.

**Comment by rsyvulko** [comment] 2020-07-03 15:38
Not relevant.

**Closed by rsyvulko** 2020-07-03 15:38 UTC
Labels: Admin, Bug, Pri: medium, Sev: trivial, front-end
